---
name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Test
        run: "go test ./..."